### PR TITLE
fix: Small changes from comment

### PR DESCRIPTION
**Pull request by eliotwrobson**
Some small changes suggested by this comment from the review: https://github.com/pyOpenSci/software-submission/issues/152#issuecomment-1900695651

Ran the build command locally and seems to work? Not 1000% sure if I tested this correctly, but I think fairly reasonable changes.

### CODE REVIEW

**Review by caleb531 — APPROVED** [review]
@eliotwrobson I read Leah's comment from the review thread, and this makes sense to me! It's also nice to know some of these practices are no longer necessary.

Approved!

**Comment by caleb531** [comment]
@eliotwrobson BTW, feel free to merge these housekeeping changes into `main`. I also assume we don't need to publish another release given the nature of these changes.

**Comment by caleb531** [comment]
@eliotwrobson But maybe first double-check that there aren't any other code changes that might be inadvertently merged in.

**Comment by eliotwrobson** [comment]
@caleb531 merged to main! The only new commit was the one generated from this PR.

**Pull request merged**
