### PR TITLE
Add __init__.py to every module.

### PR DESCRIPTION
**Pull request by YtvwlD**
Those files not existing trips up some interpreters (eg. bpython).

### CODE REVIEW

**Comment by caleb531** [comment]
@YtvwlD Good call—thanks for the PR. :)

**Comment by rjptechsolutions** [comment]
Can you give some proper examples of it how to implement this Lib... Like nfa to dfa convert  with user input

**Comment by YtvwlD** [comment]
There is a [README](https://github.com/caleb531/automata#dfafrom_nfacls-nfa) which should answer this question.

**Comment by caleb531** [comment]
@rjptechsolutions In particular, see the `DFA.from_nfa()` section (and the section immediately following, which shows you how to create an NFA):
https://github.com/caleb531/automata#dfafrom_nfacls-nfa

**Pull request merged**
