### PR TITLE
Initial immutability rewrites

### PR DESCRIPTION
**Pull request by eliotwrobson**
Putting up as a draft PR because my local test runner is being weird. Part of inital set of rewrites in preparation for enforcing immutability.

### CODE REVIEW

**Comment by eliotwrobson** [comment]
@caleb531 all the rewrites should be working aside from the `eliminate_lambda`. Will take another crack at it sometime tomorrow I think, but feel free to commit directly to this branch if you can figure it out.

**Comment by caleb531** [comment]
@eliotwrobson Sounds good to me. I would definitely agree about having an additional test scenario to cover the edge cases.

The code looks fine currently, so please carry along.

**Review by caleb531 — APPROVED** [review]
@eliotwrobson This looks great! Just to confirm, were you planning to take a look at the *PDA and *TM classes as well? Because I can take those on if you want to stay focused on the *FA types, or don't have the time.

**Comment by eliotwrobson** [comment]
@caleb531 Yeah I'm a bit busy, I can handle the DFA/NFA types (this effectively does that, I think). It would be great if you could take a look at the *PDA and *TM classes. I can try and take a look at the GNFA if I have time. I think the main internal rewrites were in the DFA/NFA classes, so the bulk of the remaining changes are going to be in test cases.

**Comment by eliotwrobson** [comment]
@caleb531 Sounds good! If you're planning on adding updates to the tests, I think I'll take a backseat for a bit (maybe I'll try my hand at some internal GNFA changes, if things wind up being very easy). Though I think you've merged all of the rewrites that we had sitting on the shelf. If I start on any large efforts, I'll be sure to give you a heads up!

The other thing that I might try my hand at before a v7 release is porting over some standard DFA creation functions from other Automata libraries I've seen around, and maybe adding a few characters to the regular expression syntax, but those can wait until all of the immutability changes have been made.

**Pull request merged**
