### PR TITLE
Make acceptance mode of PDAs configurable.

### PR DESCRIPTION
**Pull request by YtvwlD**
This is related to issue #8.

I implemented the feature (which was a small change) and adjusted the documentation and tests.
I didn't add a test for the case where one mode is specified and the other occurs, though.

### CODE REVIEW

**Comment by caleb531** [comment]
@YtvwlD Thanks for the PR! But I have one concern, on the note of backwards-compatibility, since I mentioned that was a requirement of mine in https://github.com/caleb531/automata/issues/8#issuecomment-455922942. That is, you currently have `acceptance_mode` as a required parameter. It should be an optional parameter, with the default value set to `'both'` in your function signatures. Otherwise, you would effectively be breaking everyone's existing `DPDA` and `NPDA` instances because they don't have `acceptance_mode` specified.

**Comment by YtvwlD** [comment]
Oh, yeah. Sorry about that. I'll fix it tomorrow.

**Comment by YtvwlD** [comment]
I made `both` the default and added the two tests.
I'm still unsure whether I should add a test which defines the "wrong" mode of acceptance and asserts that the input is not being accepted. This would probably make sense but I would have to remember stuff about PDAs...

**Comment by caleb531** [comment]
@YtvwlD That may be a good idea, and actually wouldn't be difficult. Simply take your existing `final_state` and `empty_stack` tests, swap the acceptance modes, then assert that the input has not been accepted in both cases.

Also, I noticed that the `_validate_acceptance` method is never called, so please add a test for that as well.

screen shot 2019-02-01 at 11 14 13 am

Those will be the final requests I make before I consider this PR perfect. Thank you for your excellent work so far. :)

**Comment by caleb531** [comment]
@YtvwlD As you can already tell, I have taken the liberty of adding these final requests of mine, so you don't have to worry about them. As it is, all tests have passed, and I am ready to merge this PR. If you have any additional work or feedback, throw it into a new issue/PR.

**Pull request merged**
